// <auto-generated />
using Ionit.Receitas.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Ionit.Receitas.Core.Migrations
{
    [DbContext(typeof(ContextMasterChef))]
    partial class ContextMasterChefModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoriaId");

                    b.Property<int>("RendimentoPorcao");

                    b.Property<int>("TempoPreparo");

                    b.Property<string>("Titulo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.ReceitaCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("ReceitaCategoria");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.ReceitaCurtida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ReceitaId");

                    b.Property<string>("Usuario");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaCurtida");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.ReceitaIngrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.Property<int?>("ReceitaId");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaIngrediente");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.ReceitaTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<int?>("ReceitaId");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaTag");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.Receita", b =>
                {
                    b.HasOne("Ionit.Receitas.Core.Entities.ReceitaCategoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.ReceitaCurtida", b =>
                {
                    b.HasOne("Ionit.Receitas.Core.Entities.Receita")
                        .WithMany("Curtidas")
                        .HasForeignKey("ReceitaId");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.ReceitaIngrediente", b =>
                {
                    b.HasOne("Ionit.Receitas.Core.Entities.Receita")
                        .WithMany("Ingredientes")
                        .HasForeignKey("ReceitaId");
                });

            modelBuilder.Entity("Ionit.Receitas.Core.Entities.ReceitaTag", b =>
                {
                    b.HasOne("Ionit.Receitas.Core.Entities.Receita")
                        .WithMany("Tags")
                        .HasForeignKey("ReceitaId");
                });
#pragma warning restore 612, 618
        }
    }
}
